Metrics/AbcSize:
  Max: 17

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 110

Naming/PredicateName:
  Exclude:
    - lib/watirsome/regions.rb

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
